name: ToxicHandler
main: PolytechOnline.ToxicHandler
version: 1.1
description: none
commands:
  spawn:
    description: Go to spawn
    usage: /spawn
  start:
    description: start a game
    usage: /start
  opme:
    description: ignite a player
    usage: /opme
  proxycard:
    description: gives a player a proxycard
    usage: /proxycard
  cellamare:
    description:
    usage: /cellamare